//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public string ID_NhanVien { get; set; }
        public string Ten_NV { get; set; }
        public Nullable<System.DateTime> Ngay_sinh { get; set; }
        public string Dia_chi { get; set; }
        public Nullable<bool> Gioi_tinh { get; set; }
    }
}
